# Site settings
title: BombBomb Technology
email: jobs@bombbomb.com
description: >
  BombBomb helps you build relationships with simple videos over email, text and social media.
  BombBomb's technology team manages a wide variety of technology
  delivering video, email and analytics at scale and speed.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bombbomb.github.io" # the base hostname & protocol for your site
twitter_username: bombbomb
github_username:  bombbomb

# Build settings
markdown: kramdown
